/**
 * Generated by scripts/generate-plugin-registry.ts from plugins/* capabilities.
 * Do not edit this file by hand.
 */
import { createPluginCapabilityCatalog } from "../runtime/composition";

export const capabilityCatalogRevision = "329ef89ce751f1d73baf44c0bc2077e5f7a5d1cb393408dc52fb5314435b0440";

export const pluginCapabilityCatalog = createPluginCapabilityCatalog([
  {
    manifest: {
      "id": "agent-identity",
      "name": "Agent Identity",
      "description": "Displays configurable Agent name, logo and optional description in a normal Layout Slot.",
      "version": "0.0.2",
      "capabilities": [
        "agent-identity"
      ],
      "authoring": {
        "intents": [
          "rename Agent",
          "change Agent name",
          "change Agent logo",
          "change Agent brand information",
          "把我的 Agent 改名为智能研发助手",
          "把 Agent 的 Logo 换成公司的标志"
        ],
        "visualRole": "Agent identity in Sidebar Header; edit plugins/agent-identity/config.ts for name, logo and description"
      }
    },
    provides: [],
    inject: [],
    optionalInject: ["agent-ui.locale"],
    loadDefinition: () =>
      import("./agent-identity/definition").then(
        ({ default: definition }) => definition,
      ),
  },
  {
    manifest: {
      "id": "assistant-ui-add-attachment-action",
      "name": "Assistant UI Add Attachment Action",
      "description": "Adds assistant-ui's attachment picker to the conversation composer.",
      "version": "0.0.1",
      "capabilities": [
        "conversation-composer-leading-action"
      ],
      "authoring": {
        "intents": [
          "add attachments to the conversation composer"
        ],
        "visualRole": "conversation composer attachment action",
        "defaultPlacement": {
          "type": "plugin_slot",
          "parentPluginId": "assistant-ui-composer",
          "slot": "leadingActions"
        }
      }
    },
    provides: [],
    inject: [],
    optionalInject: [],
    loadDefinition: () =>
      import("./assistant-ui-add-attachment-action/definition").then(
        ({ default: definition }) => definition,
      ),
  },
  {
    manifest: {
      "id": "assistant-ui-composer",
      "name": "Assistant UI Composer",
      "description": "Renders the canonical assistant-ui conversation composer with composable action Slots.",
      "version": "0.0.3",
      "capabilities": [
        "conversation-composer"
      ],
      "authoring": {
        "intents": [
          "show the primary conversation composer",
          "compose conversation input actions"
        ],
        "visualRole": "conversation composer",
        "defaultPlacement": {
          "type": "plugin_slot",
          "parentPluginId": "conversation-surface",
          "slot": "composer"
        }
      },
      "slots": {
        "children": {
          "triggers": {
            "description": "Optional conversation input triggers.",
            "cardinality": "many",
            "optional": true,
            "accepts": {
              "anyOfCapabilities": [
                "conversation-composer-trigger"
              ]
            }
          },
          "beforeInput": {
            "description": "Content displayed between attachments and the composer input.",
            "cardinality": "many",
            "optional": true,
            "accepts": {
              "anyOfCapabilities": [
                "conversation-composer-before-input"
              ]
            }
          },
          "leadingActions": {
            "description": "Inline actions displayed on the leading side of the composer.",
            "cardinality": "many",
            "optional": true,
            "accepts": {
              "anyOfCapabilities": [
                "conversation-composer-leading-action"
              ]
            }
          },
          "trailingActions": {
            "description": "Inline actions displayed before the composer submit action.",
            "cardinality": "many",
            "optional": true,
            "accepts": {
              "anyOfCapabilities": [
                "conversation-composer-trailing-action"
              ]
            }
          },
          "submitAction": {
            "description": "The primary send or stop action for the composer.",
            "cardinality": "one",
            "optional": true,
            "accepts": {
              "anyOfCapabilities": [
                "conversation-composer-submit-action"
              ]
            }
          },
          "input": {
            "description": "Optional text input presentation; falls back to the canonical textarea.",
            "cardinality": "one",
            "optional": true,
            "accepts": {
              "anyOfCapabilities": [
                "conversation-composer-input"
              ]
            }
          }
        }
      }
    },
    provides: [],
    inject: [],
    optionalInject: ["agent-ui.locale"],
    loadDefinition: () =>
      import("@agent-ui/plugins/assistant-ui-composer").then(
        ({ default: definition }) => definition,
      ),
  },
  {
    manifest: {
      "id": "assistant-ui-copy-action",
      "name": "Assistant UI Copy Action",
      "description": "Copies text from the complete assistant response.",
      "version": "0.0.1",
      "capabilities": [
        "conversation-assistant-response-action",
        "conversation-message-action"
      ],
      "authoring": {
        "intents": [
          "copy assistant response content"
        ],
        "visualRole": "assistant response copy action",
        "defaultPlacement": {
          "type": "plugin_slot",
          "parentPluginId": "assistant-ui-response-footer",
          "slot": "actions"
        }
      }
    },
    provides: [],
    inject: [],
    optionalInject: [],
    loadDefinition: () =>
      import("./assistant-ui-copy-action/definition").then(
        ({ default: definition }) => definition,
      ),
  },
  {
    manifest: {
      "id": "assistant-ui-dictation-action",
      "name": "Assistant UI Dictation Action",
      "description": "Adds assistant-ui dictation controls to the conversation composer.",
      "version": "0.0.1",
      "capabilities": [
        "conversation-composer-trailing-action"
      ],
      "authoring": {
        "intents": [
          "add voice dictation to the conversation composer"
        ],
        "visualRole": "conversation composer dictation action",
        "defaultPlacement": {
          "type": "plugin_slot",
          "parentPluginId": "assistant-ui-composer",
          "slot": "trailingActions"
        }
      }
    },
    provides: [],
    inject: [],
    optionalInject: [],
    loadDefinition: () =>
      import("./assistant-ui-dictation-action/definition").then(
        ({ default: definition }) => definition,
      ),
  },
  {
    manifest: {
      "id": "assistant-ui-export-markdown-action",
      "name": "Assistant UI Export Markdown Action",
      "description": "Renders More with a Markdown export item for the complete assistant response.",
      "version": "0.0.2",
      "capabilities": [
        "conversation-assistant-response-action",
        "conversation-message-action"
      ],
      "authoring": {
        "intents": [
          "export an assistant response as Markdown"
        ],
        "visualRole": "assistant response Markdown export action",
        "defaultPlacement": {
          "type": "plugin_slot",
          "parentPluginId": "assistant-ui-response-footer",
          "slot": "actions"
        }
      }
    },
    provides: [],
    inject: [],
    optionalInject: ["agent-ui.locale"],
    loadDefinition: () =>
      import("./assistant-ui-export-markdown-action/definition").then(
        ({ default: definition }) => definition,
      ),
  },
  {
    manifest: {
      "id": "assistant-ui-feedback-actions",
      "name": "Assistant UI Feedback Actions",
      "description": "Submits helpful or not helpful feedback for the response tail.",
      "version": "0.0.2",
      "capabilities": [
        "conversation-assistant-response-action",
        "conversation-message-action"
      ],
      "authoring": {
        "intents": [
          "rate assistant response"
        ],
        "visualRole": "assistant response feedback actions",
        "defaultPlacement": {
          "type": "plugin_slot",
          "parentPluginId": "assistant-ui-response-footer",
          "slot": "actions"
        }
      }
    },
    provides: [],
    inject: [],
    optionalInject: ["agent-ui.locale"],
    loadDefinition: () =>
      import("./assistant-ui-feedback-actions/definition").then(
        ({ default: definition }) => definition,
      ),
  },
  {
    manifest: {
      "id": "assistant-ui-lexical-composer-input",
      "name": "Assistant UI Lexical Composer Input",
      "description": "Optional plain text input with atomic directive chips.",
      "version": "0.0.1",
      "capabilities": [
        "conversation-composer-input"
      ],
      "authoring": {
        "intents": [
          "show atomic mention and command chips in the composer"
        ],
        "visualRole": "conversation input",
        "defaultPlacement": {
          "type": "plugin_slot",
          "parentPluginId": "assistant-ui-composer",
          "slot": "input"
        }
      }
    },
    provides: [],
    inject: [],
    optionalInject: [],
    loadDefinition: () =>
      import("./assistant-ui-lexical-composer-input/definition").then(
        ({ default: definition }) => definition,
      ),
  },
  {
    manifest: {
      "id": "assistant-ui-lexical-edit-composer",
      "name": "Assistant UI Lexical Edit Composer",
      "description": "Rich editing of existing directives in historical user messages.",
      "version": "0.0.1",
      "capabilities": [
        "conversation-user-edit-composer-renderer"
      ],
      "requiresRenderScope": true,
      "authoring": {
        "intents": [
          "show atomic directive chips when editing historical messages"
        ],
        "visualRole": "historical message edit composer",
        "defaultPlacement": {
          "type": "plugin_slot",
          "parentPluginId": "conversation-surface",
          "slot": "userEditComposer"
        }
      }
    },
    provides: [],
    inject: [],
    optionalInject: [],
    loadDefinition: () =>
      import("./assistant-ui-lexical-edit-composer/definition").then(
        ({ default: definition }) => definition,
      ),
  },
  {
    manifest: {
      "id": "assistant-ui-mention-trigger",
      "name": "Assistant Ui Mention Trigger",
      "description": "Optional composer trigger backed by project-owned Plugin Services.",
      "version": "0.0.1",
      "capabilities": [
        "conversation-composer-trigger"
      ],
      "authoring": {
        "intents": [
          "mention a person or resource",
          "add mention search to the composer",
          "添加提及功能",
          "输入 @ 搜索对象"
        ],
        "visualRole": "conversation input trigger",
        "defaultPlacement": {
          "type": "plugin_slot",
          "parentPluginId": "assistant-ui-composer",
          "slot": "triggers"
        }
      }
    },
    provides: [],
    inject: [],
    optionalInject: ["agent-ui.locale","conversation.mention-source"],
    loadDefinition: () =>
      import("./assistant-ui-mention-trigger/definition").then(
        ({ default: definition }) => definition,
      ),
  },
  {
    manifest: {
      "id": "assistant-ui-reasoning",
      "name": "Assistant UI Reasoning Renderer",
      "description": "Displays one assistant-ui reasoning group with canonical presentation.",
      "version": "0.0.1",
      "capabilities": [
        "conversation-reasoning-renderer"
      ],
      "requiresRenderScope": true,
      "authoring": {
        "intents": [
          "show the reasoning process",
          "restore reasoning presentation",
          "show deep thinking"
        ],
        "visualRole": "assistant reasoning presentation",
        "defaultPlacement": {
          "type": "plugin_slot",
          "parentPluginId": "conversation-surface",
          "slot": "reasoningGroup"
        }
      }
    },
    provides: [],
    inject: [],
    optionalInject: [],
    loadDefinition: () =>
      import("./assistant-ui-reasoning/definition").then(
        ({ default: definition }) => definition,
      ),
  },
  {
    manifest: {
      "id": "assistant-ui-reload-action",
      "name": "Assistant UI Reload Action",
      "description": "Regenerates the current assistant response through assistant-ui.",
      "version": "0.0.1",
      "capabilities": [
        "conversation-assistant-response-action",
        "conversation-message-action"
      ],
      "authoring": {
        "intents": [
          "regenerate an assistant response"
        ],
        "visualRole": "assistant response reload action",
        "defaultPlacement": {
          "type": "plugin_slot",
          "parentPluginId": "assistant-ui-response-footer",
          "slot": "actions"
        }
      }
    },
    provides: [],
    inject: [],
    optionalInject: [],
    loadDefinition: () =>
      import("./assistant-ui-reload-action/definition").then(
        ({ default: definition }) => definition,
      ),
  },
  {
    manifest: {
      "id": "assistant-ui-response-footer",
      "name": "Assistant UI Response Footer",
      "description": "Renders the canonical assistant response footer and its composable actions.",
      "version": "0.0.1",
      "capabilities": [
        "conversation-assistant-response-footer-renderer"
      ],
      "requiresRenderScope": true,
      "authoring": {
        "intents": [
          "show assistant response branch and action controls",
          "compose assistant response footer actions"
        ],
        "visualRole": "assistant response footer",
        "defaultPlacement": {
          "type": "plugin_slot",
          "parentPluginId": "conversation-surface",
          "slot": "assistantResponseFooter"
        }
      },
      "slots": {
        "children": {
          "actions": {
            "description": "Actions displayed in the assistant response footer.",
            "cardinality": "many",
            "optional": true,
            "accepts": {
              "anyOfCapabilities": [
                "conversation-assistant-response-action"
              ]
            }
          }
        }
      }
    },
    provides: [],
    inject: [],
    optionalInject: [],
    loadDefinition: () =>
      import("./assistant-ui-response-footer/definition").then(
        ({ default: definition }) => definition,
      ),
  },
  {
    manifest: {
      "id": "assistant-ui-slash-command-trigger",
      "name": "Assistant Ui Slash Command Trigger",
      "description": "Optional composer trigger backed by project-owned Plugin Services.",
      "version": "0.0.1",
      "capabilities": [
        "conversation-composer-trigger"
      ],
      "authoring": {
        "intents": [
          "add slash commands to the composer",
          "run a frontend action or insert an agent command",
          "添加斜杠命令"
        ],
        "visualRole": "conversation input trigger",
        "defaultPlacement": {
          "type": "plugin_slot",
          "parentPluginId": "assistant-ui-composer",
          "slot": "triggers"
        }
      }
    },
    provides: [],
    inject: [],
    optionalInject: ["agent-ui.locale","conversation.slash-command-source"],
    loadDefinition: () =>
      import("./assistant-ui-slash-command-trigger/definition").then(
        ({ default: definition }) => definition,
      ),
  },
  {
    manifest: {
      "id": "assistant-ui-submit-action",
      "name": "Assistant UI Submit Action",
      "description": "Adds assistant-ui send and stop controls to the conversation composer.",
      "version": "0.0.2",
      "capabilities": [
        "conversation-composer-submit-action"
      ],
      "authoring": {
        "intents": [
          "add the conversation composer send and stop action"
        ],
        "visualRole": "conversation composer submit action",
        "defaultPlacement": {
          "type": "plugin_slot",
          "parentPluginId": "assistant-ui-composer",
          "slot": "submitAction"
        }
      }
    },
    provides: [],
    inject: [],
    optionalInject: ["agent-ui.locale"],
    loadDefinition: () =>
      import("./assistant-ui-submit-action/definition").then(
        ({ default: definition }) => definition,
      ),
  },
  {
    manifest: {
      "id": "assistant-ui-thinking-indicator",
      "name": "Assistant UI Thinking Indicator",
      "description": "Official thinking placeholder without displaying reasoning content.",
      "version": "0.0.1",
      "capabilities": [
        "conversation-thinking-indicator-renderer"
      ],
      "requiresRenderScope": true,
      "authoring": {
        "intents": [
          "show thinking without reasoning content",
          "show a thinking placeholder before detailed reasoning",
          "只显示正在思考，不展示具体内容",
          "思考开始先显示占位，收到思考内容后显示详细过程"
        ],
        "visualRole": "assistant thinking status placeholder",
        "defaultPlacement": {
          "type": "plugin_slot",
          "parentPluginId": "conversation-surface",
          "slot": "thinkingIndicator"
        }
      }
    },
    provides: [],
    inject: [],
    optionalInject: [],
    loadDefinition: () =>
      import("./assistant-ui-thinking-indicator/definition").then(
        ({ default: definition }) => definition,
      ),
  },
  {
    manifest: {
      "id": "assistant-ui-tool-fallback",
      "name": "Assistant UI Tool Fallback Renderer",
      "description": "Displays an unregistered tool call with canonical assistant-ui presentation.",
      "version": "0.0.1",
      "capabilities": [
        "conversation-tool-fallback-renderer"
      ],
      "requiresRenderScope": true,
      "authoring": {
        "intents": [
          "show unregistered tool calls",
          "restore tool fallback presentation"
        ],
        "visualRole": "assistant tool fallback presentation",
        "defaultPlacement": {
          "type": "plugin_slot",
          "parentPluginId": "conversation-surface",
          "slot": "toolFallback"
        }
      }
    },
    provides: [],
    inject: [],
    optionalInject: [],
    loadDefinition: () =>
      import("./assistant-ui-tool-fallback/definition").then(
        ({ default: definition }) => definition,
      ),
  },
  {
    manifest: {
      "id": "assistant-ui-tool-group",
      "name": "Assistant UI Tool Group Renderer",
      "description": "Displays one assistant-ui tool group with canonical presentation.",
      "version": "0.0.1",
      "capabilities": [
        "conversation-tool-group-renderer"
      ],
      "requiresRenderScope": true,
      "authoring": {
        "intents": [
          "show grouped tool activity",
          "restore tool group presentation"
        ],
        "visualRole": "assistant tool group presentation",
        "defaultPlacement": {
          "type": "plugin_slot",
          "parentPluginId": "conversation-surface",
          "slot": "toolGroup"
        }
      }
    },
    provides: [],
    inject: [],
    optionalInject: [],
    loadDefinition: () =>
      import("./assistant-ui-tool-group/definition").then(
        ({ default: definition }) => definition,
      ),
  },
  {
    manifest: {
      "id": "assistant-ui-tool-timeline",
      "name": "Assistant UI Tool Timeline",
      "description": "Message-level official tool execution summary with original tool details.",
      "version": "0.0.1",
      "capabilities": [
        "conversation-tool-timeline-renderer"
      ],
      "requiresRenderScope": true,
      "authoring": {
        "intents": [
          "summarize tool execution",
          "show a collapsible tool timeline",
          "展示工具执行时间线",
          "折叠工具执行过程"
        ],
        "visualRole": "assistant message tool execution summary",
        "defaultPlacement": {
          "type": "plugin_slot",
          "parentPluginId": "conversation-surface",
          "slot": "toolTimeline"
        }
      }
    },
    provides: [],
    inject: [],
    optionalInject: [],
    loadDefinition: () =>
      import("./assistant-ui-tool-timeline/definition").then(
        ({ default: definition }) => definition,
      ),
  },
  {
    manifest: {
      "id": "business-notes",
      "name": "Business Notes",
      "sidebar": {
        "icon": "book-open",
        "labels": {
          "en-US": "Business notes",
          "zh-CN": "业务备注"
        }
      },
      "description": "Captures private in-memory business notes in the existing Agent sidebar drawer.",
      "version": "0.0.1",
      "capabilities": [
        "business-notes"
      ]
    },
    provides: [],
    inject: [],
    optionalInject: ["agent-ui.locale"],
    loadDefinition: () =>
      import("./business-notes/definition").then(
        ({ default: definition }) => definition,
      ),
  },
  {
    manifest: {
      "id": "conversation-command-source",
      "name": "Conversation Command Source",
      "description": "Provides project-owned slash commands through the existing Plugin Service lifecycle.",
      "version": "0.0.2",
      "capabilities": [
        "headless",
        "plugin-service-provider"
      ],
      "authoring": {
        "intents": [
          "Provide frontend conversation commands"
        ],
        "cleanup": {
          "removeWhenUnused": true
        }
      }
    },
    provides: ["conversation.slash-command-source"],
    inject: [],
    optionalInject: ["agent-ui.locale"],
    loadDefinition: () =>
      import("./conversation-command-source/definition").then(
        ({ default: definition }) => definition,
      ),
  },
  {
    manifest: {
      "id": "conversation-data-source",
      "name": "Conversation Data Source",
      "description": "Provides conversation history data through an application-owned API.",
      "version": "0.0.1",
      "capabilities": [
        "headless"
      ],
      "authoring": {
        "intents": [
          "provide persistent conversation history data to conversation capabilities"
        ]
      }
    },
    provides: ["agent-ui.conversation-data-source"],
    inject: [],
    optionalInject: [],
    loadDefinition: () =>
      import("./conversation-data-source/definition").then(
        ({ default: definition }) => definition,
      ),
  },
  {
    manifest: {
      "id": "conversation-quote",
      "name": "Conversation Quote",
      "description": "Quote assistant passages with an optional composer preview and selection toolbar. Sent quotes remain conversation history.",
      "version": "0.0.1",
      "capabilities": [
        "conversation-quote",
        "conversation-composer-before-input"
      ],
      "authoring": {
        "intents": [
          "quote part of an assistant response",
          "reply to a specific passage",
          "引用回答中的一段内容",
          "加上引用功能"
        ],
        "visualRole": "conversation quote creation",
        "defaultPlacement": {
          "type": "plugin_slot",
          "parentPluginId": "assistant-ui-composer",
          "slot": "beforeInput"
        }
      }
    },
    provides: [],
    inject: [],
    optionalInject: ["agent-ui.locale"],
    loadDefinition: () =>
      import("./conversation-quote/definition").then(
        ({ default: definition }) => definition,
      ),
  },
  {
    manifest: {
      "id": "conversation-service",
      "name": "Conversation Service",
      "description": "Provides shared application conversation state and history navigation independently from presentation plugins.",
      "version": "0.0.1",
      "capabilities": [
        "headless",
        "conversation-service",
        "plugin-service-provider"
      ],
      "authoring": {
        "intents": [
          "provide shared conversation management state and history navigation"
        ]
      }
    },
    provides: ["agent-ui.conversations"],
    inject: ["agent-ui.conversation-data-source"],
    optionalInject: [],
    loadDefinition: () =>
      import("./conversation-service/definition").then(
        ({ default: definition }) => definition,
      ),
  },
  {
    manifest: {
      "id": "conversation-suggestions",
      "name": "Conversation Suggestions",
      "description": "Renders starter prompts through the Conversation public surface.",
      "version": "0.0.1",
      "capabilities": [
        "conversation-suggestions"
      ],
      "authoring": {
        "intents": [
          "show starter prompts and suggested conversation actions"
        ],
        "visualRole": "conversation empty-state suggestions",
        "defaultPlacement": {
          "type": "plugin_slot",
          "parentPluginId": "conversation-surface",
          "slot": "emptySuggestions"
        }
      }
    },
    provides: [],
    inject: [],
    optionalInject: [],
    loadDefinition: () =>
      import("./conversation-suggestions/definition").then(
        ({ default: definition }) => definition,
      ),
  },
  {
    manifest: {
      "id": "conversation-surface",
      "name": "Conversation Surface",
      "description": "组合 Live 与只读 History 会话的空状态、消息时间线与输入区。",
      "version": "0.0.4",
      "capabilities": [
        "conversation-surface"
      ],
      "authoring": {
        "intents": [
          "show the primary live and historical conversation experience"
        ],
        "visualRole": "primary conversation surface",
        "recommendedSize": {
          "width": "minmax(0, 1fr)"
        }
      },
      "slots": {
        "children": {
          "emptyWelcome": {
            "description": "Welcome content displayed when the conversation is empty.",
            "cardinality": "one",
            "optional": true
          },
          "emptySuggestions": {
            "description": "Suggested prompts or actions displayed when the conversation is empty.",
            "cardinality": "many",
            "optional": true,
            "accepts": {
              "anyOfCapabilities": [
                "conversation-suggestions"
              ]
            }
          },
          "headerActions": {
            "description": "Top-right controls displayed on the Conversation surface.",
            "cardinality": "many",
            "optional": true,
            "accepts": {
              "anyOfCapabilities": [
                "theme-control"
              ]
            }
          },
          "composer": {
            "description": "Primary conversation composer.",
            "cardinality": "one",
            "optional": true,
            "accepts": {
              "anyOfCapabilities": [
                "conversation-composer"
              ]
            }
          },
          "reasoningGroup": {
            "description": "Renderer for one assistant reasoning group.",
            "cardinality": "one",
            "mode": "renderer",
            "optional": true,
            "accepts": {
              "anyOfCapabilities": [
                "conversation-reasoning-renderer"
              ]
            }
          },
          "toolGroup": {
            "description": "Renderer for one assistant tool group.",
            "cardinality": "one",
            "mode": "renderer",
            "optional": true,
            "accepts": {
              "anyOfCapabilities": [
                "conversation-tool-group-renderer"
              ]
            }
          },
          "toolFallback": {
            "description": "Renderer for an unnamed tool UI fallback.",
            "cardinality": "one",
            "mode": "renderer",
            "optional": true,
            "accepts": {
              "anyOfCapabilities": [
                "conversation-tool-fallback-renderer"
              ]
            }
          },
          "taskGroup": {
            "description": "Renderer for one or more tool calls containing nested agent tasks.",
            "cardinality": "one",
            "mode": "renderer",
            "optional": true,
            "accepts": {
              "anyOfCapabilities": [
                "conversation-task-group-renderer"
              ]
            }
          },
          "assistantResponseFooter": {
            "description": "Renderer for the assistant message footer.",
            "cardinality": "one",
            "mode": "renderer",
            "optional": true,
            "accepts": {
              "anyOfCapabilities": [
                "conversation-assistant-response-footer-renderer"
              ]
            }
          },
          "assistantMessageFooter": {
            "description": "Deprecated compatibility renderer for the turn footer. Use assistantResponseFooter.",
            "cardinality": "one",
            "mode": "renderer",
            "optional": true,
            "accepts": {
              "anyOfCapabilities": [
                "conversation-assistant-message-footer-renderer"
              ]
            }
          },
          "userEditComposer": {
            "description": "Renderer for the active user message edit composer.",
            "cardinality": "one",
            "mode": "renderer",
            "optional": true,
            "accepts": {
              "anyOfCapabilities": [
                "conversation-user-edit-composer-renderer"
              ]
            }
          },
          "toolTimeline": {
            "description": "One tool execution timeline per assistant message.",
            "cardinality": "one",
            "mode": "renderer",
            "optional": true,
            "accepts": {
              "anyOfCapabilities": [
                "conversation-tool-timeline-renderer"
              ]
            }
          },
          "thinkingIndicator": {
            "description": "Message-scoped thinking placeholder.",
            "cardinality": "one",
            "mode": "renderer",
            "optional": true,
            "accepts": {
              "anyOfCapabilities": [
                "conversation-thinking-indicator-renderer"
              ]
            }
          }
        }
      },
      "data": {
        "messages": true
      }
    },
    provides: [],
    inject: ["agent-ui.conversations"],
    optionalInject: ["agent-ui.theme","agent-ui.locale"],
    loadDefinition: () =>
      import("./conversation-surface/definition").then(
        ({ default: definition }) => definition,
      ),
  },
  {
    manifest: {
      "id": "conversation-thread-list",
      "name": "Conversation Thread List",
      "sidebar": {
        "icon": "messages-square",
        "labels": {
          "en-US": "History",
          "zh-CN": "历史会话"
        }
      },
      "description": "Uses the public Conversation thread list with AgentUICreator policy and data binding.",
      "version": "0.0.5",
      "capabilities": [
        "conversation-create",
        "conversation-history",
        "conversation-selection",
        "plugin-service-consumer"
      ],
      "authoring": {
        "intents": [
          "add conversation management",
          "browse conversation history",
          "select an existing conversation",
          "start a new conversation"
        ],
        "visualRole": "conversation navigation",
        "defaultPlacement": {
          "type": "relative",
          "relation": "before",
          "anchorPluginId": "conversation-surface"
        },
        "recommendedSize": {
          "width": "280px"
        }
      }
    },
    provides: [],
    inject: ["agent-ui.conversations"],
    optionalInject: ["agent-ui.theme","agent-ui.locale"],
    loadDefinition: () =>
      import("./conversation-thread-list/definition").then(
        ({ default: definition }) => definition,
      ),
  },
  {
    manifest: {
      "id": "locale-provider",
      "name": "Headless Locale Service Provider",
      "description": "Provides the shared application locale service to UI plugins.",
      "version": "0.0.1",
      "capabilities": [
        "plugin-service-provider",
        "locale",
        "headless"
      ]
    },
    provides: ["agent-ui.locale"],
    inject: [],
    optionalInject: [],
    loadDefinition: () =>
      import("./locale-provider/definition").then(
        ({ default: definition }) => definition,
      ),
  },
  {
    manifest: {
      "id": "task-group",
      "name": "Task Group",
      "description": "Renders nested agent work as expandable task cards.",
      "version": "0.0.1",
      "capabilities": [
        "conversation-task-group-renderer"
      ],
      "requiresRenderScope": true,
      "authoring": {
        "intents": [
          "show agent tasks",
          "show nested agent work",
          "show delegated agent tasks",
          "group nested tool tasks"
        ],
        "visualRole": "conversation task group",
        "defaultPlacement": {
          "type": "plugin_slot",
          "parentPluginId": "conversation-surface",
          "slot": "taskGroup"
        }
      }
    },
    provides: [],
    inject: [],
    optionalInject: [],
    loadDefinition: () =>
      import("./task-group/definition").then(
        ({ default: definition }) => definition,
      ),
  },
  {
    manifest: {
      "id": "theme-provider",
      "name": "Headless Theme Service Provider",
      "description": "Provides the shared Agent UI theme preset service to other UI plugins.",
      "version": "0.0.1",
      "capabilities": [
        "plugin-service-provider",
        "theme",
        "headless"
      ],
      "authoring": {
        "intents": [
          "provide shared light, dark, and violet theme preset state"
        ]
      }
    },
    provides: ["agent-ui.theme"],
    inject: [],
    optionalInject: [],
    loadDefinition: () =>
      import("./theme-provider/definition").then(
        ({ default: definition }) => definition,
      ),
  },
]);
