import { validateOfficialPackageServices } from "./verify-package-services.mjs";
import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { resolveSourceRelease, verifySourceRelease, pluginSourceDigest } from '../src/release.ts';
const args = process.argv.slice(2);
const positional = args.filter(arg => !arg.startsWith('--'));
const targetRoot = path.resolve(positional[0] ?? new URL('../registry', import.meta.url).pathname);
const previousLocation = positional[1] ?? process.env.AGENT_UI_PREVIOUS_RELEASE_ROOT;
const initialRelease = process.env.AGENT_UI_INITIAL_RELEASE === '1';
if (args.includes('--publish') && !previousLocation && !initialRelease) throw new Error('Publishing requires AGENT_UI_PREVIOUS_RELEASE_ROOT pointing to the previous official release, or AGENT_UI_INITIAL_RELEASE=1 for the first release.');
const previousRoot = previousLocation ? path.resolve(previousLocation) : new URL('../fixtures/releases/0.0.1', import.meta.url).pathname;
const previous = args.includes('--publish') && initialRelease && !previousLocation ? undefined : await resolveSourceRelease(previousRoot);
if (args.includes('--publish')) {
  const pkg = JSON.parse(await readFile(new URL('../package.json', import.meta.url), 'utf8'));
  const manifest = JSON.parse(await readFile(path.join(targetRoot, 'release.json'), 'utf8'));
  if (pkg.version !== manifest.releaseVersion) throw new Error('Package version must match releaseVersion');
}
if (!args.includes('--verify')) {
  // Descriptions are authored by the release owner, never generated by Creator.
  const descriptor = JSON.parse(await readFile(path.join(targetRoot, 'release.json'), 'utf8'));
  const { loadAgentUISourceRegistry } = await import('../src/loader.ts');
  const registry = await loadAgentUISourceRegistry(targetRoot);
  for (const item of registry.items.filter(item => item.id.startsWith('plugin/'))) {
    const old = previous?.registry.byId.get(item.id);
    const id = item.id.slice(7);
    if (old && pluginSourceDigest(old) !== pluginSourceDigest(item) && descriptor.plugins[id].version === previous.descriptor.plugins[id].version) {
      const components = previous.descriptor.plugins[id].version.split('.').map(Number);
      components[2]++;
      const version = components.join('.');
      const manifestFile = item.loadedFiles.find(file => file.target === `plugins/${id}/manifest.json`).absolutePath;
      const manifest = JSON.parse(await readFile(manifestFile, 'utf8'));
      manifest.version = version;
      await writeFile(manifestFile, JSON.stringify(manifest, null, 2) + '\n');
      descriptor.plugins[id].version = version;
    }
  }
  await writeFile(path.join(targetRoot, 'release.json'), JSON.stringify(descriptor, null, 2) + '\n');
}
const target = await resolveSourceRelease(targetRoot);
await validateOfficialPackageServices(target.registry);
verifySourceRelease(target, previous);
console.log('Release metadata verified against ' + (previous?.descriptor.releaseVersion ?? 'initial release'));
