import { createHash } from "node:crypto";
import { readFile } from "node:fs/promises";
import path from "node:path";

import type { SourceFile, Statement } from "typescript/unstable/ast";
import {
  isExportAssignment,
  isExportDeclaration,
  isNamedExports,
} from "typescript/unstable/ast/is";
import { API, ModifierFlags } from "typescript/unstable/sync";

import {
  collectAppUIPluginLocations,
  type AppUIModel,
} from "../../framework/contracts/app-ui-model";
import { AppUICompilerError, compileAppUIModel } from "../../framework/contracts/app-ui-compiler";
import {
  AppUICompositionError,
  type PluginSlotCatalog,
  type PluginCompositionCatalog,
} from "../../framework/contracts/app-ui-composition";
import { uiProjectControlConfig } from "./project-config";
import { collectPluginAssets, pathExists } from "./plugin-assets";
import {
  analyzePluginServiceDeclarations,
  inspectUIServiceDependencies,
  type AnalyzedDeclarations,
} from "./service-dependency-inspector";
import type {
  GeneratePluginCatalogResult,
  PluginAsset,
  ProjectIssue,
  UIProjectControlConfig,
} from "./types";

export const GENERATED_PLUGIN_REGISTRY_PATH = "plugins/registry.generated.ts";
export const PLUGIN_REGISTRY_ENTRY_PATH = "plugins/index.ts";
export const PLUGIN_REGISTRY_ENTRY_SOURCE =
  [
    'export {',
    '  capabilityCatalogRevision,',
    '  pluginCapabilityCatalog,',
    '} from "./registry.generated";',
    '',
  ].join("\n");

function statementHasDefaultModifier(statement: Statement): boolean {
  if (!("modifierFlags" in statement)) {
    return false;
  }
  return (
    typeof statement.modifierFlags === "number" &&
    (statement.modifierFlags & ModifierFlags.Default) !== 0
  );
}

function hasDefaultExport(sourceFile: SourceFile): boolean {
  return sourceFile.statements.some((statement) => {
    if (isExportAssignment(statement)) {
      return !statement.isExportEquals;
    }
    if (statementHasDefaultModifier(statement)) {
      return true;
    }
    return (
      isExportDeclaration(statement) &&
      statement.exportClause !== undefined &&
      isNamedExports(statement.exportClause) &&
      statement.exportClause.elements.some(
        (element) => element.name.text === "default",
      )
    );
  });
}

function catalogRevision(
  assets: readonly PluginAsset[],
  declarationsByPluginId: ReadonlyMap<string, {
    provides: string[];
    inject: string[];
    optionalInject: string[];
  }>,
): string {
  const catalog = assets.map((asset) => ({
    directory: asset.directory,
    manifest: asset.manifest,
    serviceContract: declarationsByPluginId.get(asset.pluginId) ?? {
      provides: [],
      inject: [],
      optionalInject: [],
    },
  }));
  return createHash("sha256").update(JSON.stringify(catalog)).digest("hex");
}

function capabilityCatalogSource(
  assets: readonly PluginAsset[],
  revision: string,
  declarationsByPluginId: ReadonlyMap<string, {
    provides: string[];
    inject: string[];
    optionalInject: string[];
  }>,
): string {
  const entries = assets.flatMap((asset) => {
    const declaration = declarationsByPluginId.get(asset.pluginId);
    return [
    "  {",
    `    manifest: ${JSON.stringify(asset.manifest, null, 2).replaceAll("\n", "\n    ")},`,
    `    provides: ${JSON.stringify(declaration?.provides ?? [])},`,
    `    inject: ${JSON.stringify(declaration?.inject ?? [])},`,
    `    optionalInject: ${JSON.stringify(declaration?.optionalInject ?? [])},`,
    "    loadDefinition: () =>",
    `      import("./${asset.directory}/definition").then(`,
    "        ({ default: definition }) => definition,",
    "      ),",
    "  },",
    ];
  });

  return [
    "/**",
    " * Generated by scripts/generate-plugin-registry.ts from plugins/* capabilities.",
    " * Do not edit this file by hand.",
    " */",
    'import { createPluginCapabilityCatalog } from "../runtime/composition";',
    "",
    `export const capabilityCatalogRevision = "${revision}";`,
    "",
    "export const pluginCapabilityCatalog = createPluginCapabilityCatalog([",
    ...entries,
    "]);",
    "",
  ].join("\n");
}

export async function generatePluginRegistry(
  projectRoot: string,
  model: AppUIModel,
  config: UIProjectControlConfig = uiProjectControlConfig,
): Promise<GeneratePluginCatalogResult> {
  const inventory = await collectPluginAssets(projectRoot, config);
  const errors: ProjectIssue[] = [...inventory.errors];
  const canAnalyzeServiceContracts = await pathExists(
    path.join(projectRoot, "tsconfig.json"),
  );
  const declarations: AnalyzedDeclarations = canAnalyzeServiceContracts
    ? analyzePluginServiceDeclarations(projectRoot, inventory.assets)
    : { plugins: [], issues: [], seamPaths: new Map() };
  errors.push(...declarations.issues);
  const declarationsByPluginId = new Map(
    declarations.plugins.map((declaration) => [declaration.pluginId, declaration]),
  );
  const capabilityCatalogRevision = catalogRevision(
    inventory.assets,
    declarationsByPluginId,
  );
  const selectedPluginIds = [
    ...new Set(
      collectAppUIPluginLocations(model).map(({ plugin }) => plugin.pluginId),
    ),
  ].sort();
  const assetsById = new Map<string, PluginAsset[]>();

  for (const asset of inventory.assets) {
    const matches = assetsById.get(asset.pluginId) ?? [];
    matches.push(asset);
    assetsById.set(asset.pluginId, matches);
  }

  const resolvedAssets: PluginAsset[] = [];
  const slotCatalogEntries: Array<readonly [string, NonNullable<PluginAsset["childSlots"]>]> = [];
  for (const pluginId of selectedPluginIds) {
    const matches = assetsById.get(pluginId) ?? [];
    if (matches.length === 1) {
      slotCatalogEntries.push([
        pluginId,
        matches[0]?.childSlots ?? {},
      ]);
    }
  }
  const slotCatalog: PluginSlotCatalog = Object.fromEntries(
    slotCatalogEntries,
  );
  const selectedAssets: Array<{
    asset: PluginAsset;
    definitionPath: string;
  }> = [];
  for (const pluginId of selectedPluginIds) {
    const matches = assetsById.get(pluginId) ?? [];
    if (matches.length === 0) {
      errors.push({
        code: "selected-plugin-asset-missing",
        message: `AppUIModel selects UI plugin "${pluginId}", but no matching plugins/*/manifest.json exists.`,
      });
      continue;
    }
    if (matches.length > 1) {
      continue;
    }

    const asset = matches[0];
    if (asset === undefined) {
      continue;
    }
    const definitionPath = path.join(projectRoot, asset.definitionPath);
    try {
      await readFile(definitionPath, "utf8");
    } catch (error) {
      errors.push({
        code: "selected-plugin-definition-missing",
        message: `${asset.definitionPath}: ${
          error instanceof Error ? error.message : String(error)
        }`,
      });
      continue;
    }

    selectedAssets.push({ asset, definitionPath });
  }

  if (selectedAssets.length > 0) {
    const api = new API();
    try {
      const snapshot = api.updateSnapshot({
        openFiles: selectedAssets.map(({ definitionPath }) => definitionPath),
      });
      for (const { asset, definitionPath } of selectedAssets) {
        const project = snapshot.getDefaultProjectForFile(definitionPath);
        if (project === undefined) {
          errors.push({
            code: "selected-plugin-definition-parse",
            message: `${asset.definitionPath} could not be parsed by TypeScript.`,
          });
          continue;
        }
        const sourceFile = project.program.getSourceFile(definitionPath);
        if (sourceFile === undefined) {
          errors.push({
            code: "selected-plugin-definition-parse",
            message: `${asset.definitionPath} is not part of the TypeScript project.`,
          });
          continue;
        }
        if (
          project.program.getSyntacticDiagnostics(definitionPath).length > 0
        ) {
          errors.push({
            code: "selected-plugin-definition-parse",
            message: `${asset.definitionPath} contains TypeScript syntax errors.`,
          });
          continue;
        }
        if (!hasDefaultExport(sourceFile)) {
          errors.push({
            code: "selected-plugin-default-export-missing",
            message: `${asset.definitionPath} must default-export its UIPluginDefinition.`,
          });
          continue;
        }

        resolvedAssets.push(asset);
      }
      snapshot.dispose();
    } finally {
      api.close();
    }
  }

  const compositionCatalog: PluginCompositionCatalog = Object.fromEntries(
    resolvedAssets.map((asset) => {
      const declaration = declarationsByPluginId.get(asset.pluginId);
      return [
        asset.pluginId,
        {
          childSlots: asset.childSlots ?? {},
          ...(asset.applicationGate === undefined
            ? {}
            : { applicationGate: asset.applicationGate }),
          capabilities: asset.capabilities,
          provides: declaration?.provides ?? [],
          inject: declaration?.inject ?? [],
        },
      ] as const;
    }),
  );

  try {
    compileAppUIModel(model, compositionCatalog);
  } catch (error) {
    if (error instanceof AppUICompositionError || error instanceof AppUICompilerError) {
      errors.push(...error.issues);
    } else {
      throw error;
    }
  }

  return {
    capabilityCatalog: {
      source: capabilityCatalogSource(
        inventory.assets,
        capabilityCatalogRevision,
        declarationsByPluginId,
      ),
      revision: capabilityCatalogRevision,
      pluginIds: inventory.assets.map((asset) => asset.pluginId),
    },
    activeComposition: {
      selectedPluginIds,
      resolvedPluginIds: resolvedAssets.map((asset) => asset.pluginId),
      headlessPluginIds: resolvedAssets
        .filter((asset) => asset.capabilities.includes("headless"))
        .map((asset) => asset.pluginId),
      slotCatalog,
      compositionCatalog,
    },
    assets: inventory.assets,
    serviceDependencies: inspectUIServiceDependencies(
      projectRoot,
      model,
      inventory.assets,
      declarations,
    ),
    errors,
  };
}
