import { createHash } from "node:crypto";
import { readFile } from "node:fs/promises";
import path from "node:path";

import type { SourceFile, Statement } from "typescript/unstable/ast";
import {
  isExportAssignment,
  isExportDeclaration,
  isNamedExports,
} from "typescript/unstable/ast/is";
import { API, ModifierFlags } from "typescript/unstable/sync";

import {
  collectAppUIPluginLocations,
  type AppUIModel,
} from "../../framework/contracts/app-ui-model";
import { AppUICompilerError, compileAppUIModel } from "../../framework/contracts/app-ui-compiler";
import {
  AppUICompositionError,
  type PluginSlotCatalog,
  type PluginCompositionCatalog,
} from "../../framework/contracts/app-ui-composition";
import type { AgentUIProjectPaths } from "./agent-ui-project-paths";
import { collectPluginAssets, pathExists } from "./plugin-assets";
import {
  analyzePluginServiceDeclarations,
  inspectUIServiceDependenciesFromDeclarations,
  type AnalyzedDeclarations,
} from "./service-dependency-inspector";
import type {
  GeneratePluginCatalogResult,
  PluginAsset,
  PluginProjectFacts,
  ProjectIssue,
  UIProjectControlConfig,
} from "./types";

/** Legacy V1 fixture paths. Production paths come from AgentUIProjectPaths. */
export const GENERATED_PLUGIN_REGISTRY_PATH = "plugins/registry.generated.ts";
/** Legacy V1 fixture path. Production paths come from AgentUIProjectPaths. */
export const PLUGIN_REGISTRY_ENTRY_PATH = "plugins/index.ts";
export const PLUGIN_REGISTRY_ENTRY_SOURCE =
  [
    'export {',
    '  capabilityCatalogRevision,',
    '  pluginCapabilityCatalog,',
    '} from "./registry.generated";',
    '',
  ].join("\n");

function statementHasDefaultModifier(statement: Statement): boolean {
  if (!("modifierFlags" in statement)) {
    return false;
  }
  return (
    typeof statement.modifierFlags === "number" &&
    (statement.modifierFlags & ModifierFlags.Default) !== 0
  );
}

function hasDefaultExport(sourceFile: SourceFile): boolean {
  return sourceFile.statements.some((statement) => {
    if (isExportAssignment(statement)) {
      return !statement.isExportEquals;
    }
    if (statementHasDefaultModifier(statement)) {
      return true;
    }
    return (
      isExportDeclaration(statement) &&
      statement.exportClause !== undefined &&
      isNamedExports(statement.exportClause) &&
      statement.exportClause.elements.some(
        (element) => element.name.text === "default",
      )
    );
  });
}

function catalogRevision(
  assets: readonly PluginAsset[],
  declarationsByPluginId: ReadonlyMap<string, {
    provides: string[];
    inject: string[];
    optionalInject: string[];
  }>,
): string {
  const catalog = assets.map((asset) => ({
    directory: asset.directory,
    manifest: asset.manifest,
    serviceContract: declarationsByPluginId.get(asset.pluginId) ?? {
      provides: [],
      inject: [],
      optionalInject: [],
    },
  }));
  return createHash("sha256").update(JSON.stringify(catalog)).digest("hex");
}

function capabilityCatalogSource(
  assets: readonly PluginAsset[],
  revision: string,
  declarationsByPluginId: ReadonlyMap<string, {
    provides: string[];
    inject: string[];
    optionalInject: string[];
  }>,
): string {
  const entries = assets.flatMap((asset) => {
    const declaration = declarationsByPluginId.get(asset.pluginId);
    return [
    "  {",
    `    manifest: ${JSON.stringify(asset.manifest, null, 2).replaceAll("\n", "\n    ")},`,
    `    provides: ${JSON.stringify(declaration?.provides ?? [])},`,
    `    inject: ${JSON.stringify(declaration?.inject ?? [])},`,
    `    optionalInject: ${JSON.stringify(declaration?.optionalInject ?? [])},`,
    "    loadDefinition: () =>",
    `      import("./${asset.directory}/definition").then(`,
    "        ({ default: definition }) => definition,",
    "      ),",
    "  },",
    ];
  });

  return [
    "/**",
    " * Generated by scripts/generate-plugin-registry.ts from plugins/* capabilities.",
    " * Do not edit this file by hand.",
    " */",
    'import { createPluginCapabilityCatalog } from "../runtime/composition";',
    "",
    `export const capabilityCatalogRevision = "${revision}";`,
    "",
    "export const pluginCapabilityCatalog = createPluginCapabilityCatalog([",
    ...entries,
    "]);",
    "",
  ].join("\n");
}

function addDefinitionIssue(
  issuesByPath: Map<string, ProjectIssue[]>,
  asset: PluginAsset,
  issue: ProjectIssue,
): void {
  const issues = issuesByPath.get(asset.definitionPath) ?? [];
  issues.push(issue);
  issuesByPath.set(asset.definitionPath, issues);
}

async function collectPluginDefinitionFacts(
  projectRoot: string,
  assets: readonly PluginAsset[],
): Promise<ReadonlyMap<string, readonly ProjectIssue[]>> {
  const issuesByPath = new Map<string, ProjectIssue[]>();
  const definitionPaths: Array<{
    asset: PluginAsset;
    absolutePath: string;
  }> = [];

  for (const asset of assets) {
    const definitionPath = path.join(projectRoot, asset.definitionPath);
    try {
      await readFile(definitionPath, "utf8");
      definitionPaths.push({ asset, absolutePath: definitionPath });
    } catch (error) {
      addDefinitionIssue(issuesByPath, asset, {
        code: "selected-plugin-definition-missing",
        message: `${asset.definitionPath}: ${
          error instanceof Error ? error.message : String(error)
        }`,
        pluginId: asset.pluginId,
      });
    }
  }

  if (definitionPaths.length === 0) return issuesByPath;

  const api = new API();
  try {
    const snapshot = api.updateSnapshot({
      openFiles: definitionPaths.map(({ absolutePath }) => absolutePath),
    });
    try {
      for (const { asset, absolutePath } of definitionPaths) {
        const project = snapshot.getDefaultProjectForFile(absolutePath);
        if (project === undefined) {
          addDefinitionIssue(issuesByPath, asset, {
            code: "selected-plugin-definition-parse",
            message: `${asset.definitionPath} could not be parsed by TypeScript.`,
            pluginId: asset.pluginId,
          });
          continue;
        }
        const sourceFile = project.program.getSourceFile(absolutePath);
        if (sourceFile === undefined) {
          addDefinitionIssue(issuesByPath, asset, {
            code: "selected-plugin-definition-parse",
            message: `${asset.definitionPath} is not part of the TypeScript project.`,
            pluginId: asset.pluginId,
          });
          continue;
        }
        if (project.program.getSyntacticDiagnostics(absolutePath).length > 0) {
          addDefinitionIssue(issuesByPath, asset, {
            code: "selected-plugin-definition-parse",
            message: `${asset.definitionPath} contains TypeScript syntax errors.`,
            pluginId: asset.pluginId,
          });
          continue;
        }
        if (!hasDefaultExport(sourceFile)) {
          addDefinitionIssue(issuesByPath, asset, {
            code: "selected-plugin-default-export-missing",
            message: `${asset.definitionPath} must default-export its UIPluginDefinition.`,
            pluginId: asset.pluginId,
          });
        }
      }
    } finally {
      snapshot.dispose();
    }
  } finally {
    api.close();
  }

  return issuesByPath;
}

export async function collectPluginProjectFacts(
  projectRoot: string,
  config: UIProjectControlConfig,
  paths: AgentUIProjectPaths,
): Promise<PluginProjectFacts> {
  const inventory = await collectPluginAssets(projectRoot, paths, config);
  const canAnalyzeServiceContracts = await pathExists(
    path.join(projectRoot, "tsconfig.json"),
  );
  const declarations: AnalyzedDeclarations = canAnalyzeServiceContracts
    ? analyzePluginServiceDeclarations(projectRoot, inventory.assets)
    : { plugins: [], issues: [], seamPaths: new Map() };
  const definitionIssuesByPath = await collectPluginDefinitionFacts(
    projectRoot,
    inventory.assets,
  );
  return {
    assets: inventory.assets,
    inventoryIssues: inventory.errors,
    declarations,
    definitionIssuesByPath,
  };
}

/**
 * Pure registry/composition generation from one request-scoped project-fact
 * observation. Do not add filesystem or source-analysis work here.
 */
export function generatePluginRegistryFromFacts(
  model: AppUIModel,
  facts: PluginProjectFacts,
): GeneratePluginCatalogResult {
  const selectedPluginIds = [
    ...new Set(
      collectAppUIPluginLocations(model).map(({ plugin }) => plugin.pluginId),
    ),
  ].sort();
  const selectedPluginIdSet = new Set(selectedPluginIds);
  const errors: ProjectIssue[] = [
    ...facts.inventoryIssues,
    ...facts.declarations.issues.filter(
      (issue) =>
        issue.pluginId === undefined || selectedPluginIdSet.has(issue.pluginId),
    ),
  ];
  const declarationsByPluginId = new Map(
    facts.declarations.plugins.map((declaration) => [declaration.pluginId, declaration]),
  );
  const capabilityCatalogRevision = catalogRevision(
    facts.assets,
    declarationsByPluginId,
  );
  const assetsById = new Map<string, PluginAsset[]>();

  for (const asset of facts.assets) {
    const matches = assetsById.get(asset.pluginId) ?? [];
    matches.push(asset);
    assetsById.set(asset.pluginId, matches);
  }

  const resolvedAssets: PluginAsset[] = [];
  const slotCatalogEntries: Array<readonly [string, NonNullable<PluginAsset["childSlots"]>]> = [];
  for (const pluginId of selectedPluginIds) {
    const matches = assetsById.get(pluginId) ?? [];
    if (matches.length === 1) {
      slotCatalogEntries.push([
        pluginId,
        matches[0]?.childSlots ?? {},
      ]);
    }
  }
  const slotCatalog: PluginSlotCatalog = Object.fromEntries(
    slotCatalogEntries,
  );
  for (const pluginId of selectedPluginIds) {
    const matches = assetsById.get(pluginId) ?? [];
    if (matches.length === 0) {
      errors.push({
        code: "selected-plugin-asset-missing",
        message: `AppUIModel selects UI plugin "${pluginId}", but no matching plugins/*/manifest.json exists.`,
      });
      continue;
    }
    if (matches.length > 1) {
      continue;
    }

    const asset = matches[0];
    if (asset === undefined) {
      continue;
    }
    const definitionIssues = facts.definitionIssuesByPath.get(asset.definitionPath) ?? [];
    if (definitionIssues.length > 0) {
      errors.push(...definitionIssues);
      continue;
    }

    resolvedAssets.push(asset);
  }

  const compositionCatalog: PluginCompositionCatalog = Object.fromEntries(
    resolvedAssets.map((asset) => {
      const declaration = declarationsByPluginId.get(asset.pluginId);
      return [
        asset.pluginId,
        {
          childSlots: asset.childSlots ?? {},
          ...(asset.applicationGate === undefined
            ? {}
            : { applicationGate: asset.applicationGate }),
          capabilities: asset.capabilities,
          requiresRenderScope: asset.manifest.requiresRenderScope === true,
          provides: declaration?.provides ?? [],
          inject: declaration?.inject ?? [],
        },
      ] as const;
    }),
  );

  try {
    compileAppUIModel(model, compositionCatalog);
  } catch (error) {
    if (error instanceof AppUICompositionError || error instanceof AppUICompilerError) {
      errors.push(...error.issues);
    } else {
      throw error;
    }
  }

  return {
    capabilityCatalog: {
      source: capabilityCatalogSource(
        facts.assets,
        capabilityCatalogRevision,
        declarationsByPluginId,
      ),
      revision: capabilityCatalogRevision,
      pluginIds: facts.assets.map((asset) => asset.pluginId),
    },
    activeComposition: {
      selectedPluginIds,
      resolvedPluginIds: resolvedAssets.map((asset) => asset.pluginId),
      headlessPluginIds: resolvedAssets
        .filter((asset) => asset.capabilities.includes("headless"))
        .map((asset) => asset.pluginId),
      slotCatalog,
      compositionCatalog,
    },
    assets: facts.assets,
    serviceDependencies: inspectUIServiceDependenciesFromDeclarations(
      model,
      facts.assets,
      facts.declarations,
    ),
    errors,
  };
}

export async function generatePluginRegistry(
  projectRoot: string,
  model: AppUIModel,
  options: { readonly config: UIProjectControlConfig; readonly paths: AgentUIProjectPaths },
): Promise<GeneratePluginCatalogResult> {
  const facts = await collectPluginProjectFacts(projectRoot, options.config, options.paths);
  return generatePluginRegistryFromFacts(model, facts);
}
