import { readFile } from "node:fs/promises";
import path from "node:path";

import type { SourceFile, Statement } from "typescript/unstable/ast";
import {
  isExportAssignment,
  isExportDeclaration,
  isNamedExports,
} from "typescript/unstable/ast/is";
import { API, ModifierFlags } from "typescript/unstable/sync";

import type { AppUIModel } from "../../framework/contracts/app-ui-model";
import { uiProjectControlConfig } from "./project-config";
import { collectPluginAssets } from "./plugin-assets";
import type {
  GeneratePluginRegistryResult,
  PluginAsset,
  ProjectIssue,
  UIProjectControlConfig,
} from "./types";

export const GENERATED_PLUGIN_REGISTRY_PATH = "plugins/registry.generated.ts";
export const PLUGIN_REGISTRY_ENTRY_PATH = "plugins/index.ts";
export const PLUGIN_REGISTRY_ENTRY_SOURCE =
  'export { pluginDefinitions } from "./registry.generated";\n';

function statementHasDefaultModifier(statement: Statement): boolean {
  if (!("modifierFlags" in statement)) {
    return false;
  }
  return (
    typeof statement.modifierFlags === "number" &&
    (statement.modifierFlags & ModifierFlags.Default) !== 0
  );
}

function hasDefaultExport(sourceFile: SourceFile): boolean {
  return sourceFile.statements.some((statement) => {
    if (isExportAssignment(statement)) {
      return !statement.isExportEquals;
    }
    if (statementHasDefaultModifier(statement)) {
      return true;
    }
    return (
      isExportDeclaration(statement) &&
      statement.exportClause !== undefined &&
      isNamedExports(statement.exportClause) &&
      statement.exportClause.elements.some(
        (element) => element.name.text === "default",
      )
    );
  });
}

function registrySource(assets: readonly PluginAsset[]): string {
  const imports = assets.map(
    (asset, index) =>
      `import pluginDefinition${index} from "./${asset.directory}/definition";`,
  );
  const definitions = assets.map(
    (_asset, index) => `  pluginDefinition${index},`,
  );

  return [
    "/**",
    " * Generated by scripts/generate-plugin-registry.ts from AppUIModel.",
    " * Do not edit this file by hand.",
    " */",
    ...imports,
    "",
    "export const pluginDefinitions = [",
    ...definitions,
    "] as const;",
    "",
  ].join("\n");
}

export async function generatePluginRegistry(
  projectRoot: string,
  model: AppUIModel,
  config: UIProjectControlConfig = uiProjectControlConfig,
): Promise<GeneratePluginRegistryResult> {
  const inventory = await collectPluginAssets(projectRoot, config);
  const errors: ProjectIssue[] = [...inventory.errors];
  const selectedPluginIds = [
    ...new Set(
      Object.values(model.pluginInstances).map((instance) => instance.pluginId),
    ),
  ].sort();
  const assetsById = new Map<string, PluginAsset[]>();

  for (const asset of inventory.assets) {
    const matches = assetsById.get(asset.pluginId) ?? [];
    matches.push(asset);
    assetsById.set(asset.pluginId, matches);
  }

  const registeredAssets: PluginAsset[] = [];
  const selectedAssets: Array<{
    asset: PluginAsset;
    definitionPath: string;
  }> = [];
  for (const pluginId of selectedPluginIds) {
    const matches = assetsById.get(pluginId) ?? [];
    if (matches.length === 0) {
      errors.push({
        code: "selected-plugin-asset-missing",
        message: `AppUIModel selects UI plugin "${pluginId}", but no matching plugins/*/manifest.json exists.`,
      });
      continue;
    }
    if (matches.length > 1) {
      continue;
    }

    const asset = matches[0];
    if (asset === undefined) {
      continue;
    }
    const definitionPath = path.join(projectRoot, asset.definitionPath);
    try {
      await readFile(definitionPath, "utf8");
    } catch (error) {
      errors.push({
        code: "selected-plugin-definition-missing",
        message: `${asset.definitionPath}: ${
          error instanceof Error ? error.message : String(error)
        }`,
      });
      continue;
    }

    selectedAssets.push({ asset, definitionPath });
  }

  if (selectedAssets.length > 0) {
    const api = new API();
    try {
      const snapshot = api.updateSnapshot({
        openFiles: selectedAssets.map(({ definitionPath }) => definitionPath),
      });
      for (const { asset, definitionPath } of selectedAssets) {
        const project = snapshot.getDefaultProjectForFile(definitionPath);
        if (project === undefined) {
          errors.push({
            code: "selected-plugin-definition-parse",
            message: `${asset.definitionPath} could not be parsed by TypeScript.`,
          });
          continue;
        }
        const sourceFile = project.program.getSourceFile(definitionPath);
        if (sourceFile === undefined) {
          errors.push({
            code: "selected-plugin-definition-parse",
            message: `${asset.definitionPath} is not part of the TypeScript project.`,
          });
          continue;
        }
        if (
          project.program.getSyntacticDiagnostics(definitionPath).length > 0
        ) {
          errors.push({
            code: "selected-plugin-definition-parse",
            message: `${asset.definitionPath} contains TypeScript syntax errors.`,
          });
          continue;
        }
        if (!hasDefaultExport(sourceFile)) {
          errors.push({
            code: "selected-plugin-default-export-missing",
            message: `${asset.definitionPath} must default-export its UIPluginDefinition.`,
          });
          continue;
        }

        registeredAssets.push(asset);
      }
      snapshot.dispose();
    } finally {
      api.close();
    }
  }

  return {
    source: registrySource(registeredAssets),
    selectedPluginIds,
    registeredPluginIds: registeredAssets.map((asset) => asset.pluginId),
    headlessPluginIds: registeredAssets
      .filter((asset) => asset.capabilities.includes("headless"))
      .map((asset) => asset.pluginId),
    assets: inventory.assets,
    errors,
  };
}
