import { test, expect } from "@playwright/test";
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
test("real Creator dialogue can inspect the Sidebar after a toolbar refresh", async ({ page }) => {
  test.setTimeout(180_000);
  const evidence = path.resolve("../../docs/implementation/creator-refresh/evidence");
  const file = path.resolve("../../examples/creator-host-sandbox/src/agent-ui/app-ui/app-ui.json");
  const before = await readFile(file, "utf8");
  const errors: string[] = [];
  page.on("pageerror", error => errors.push(error.message));
  await page.goto("/dock.html");
  const input = page.locator("#creator-request");
  await expect(input).toBeEnabled();
  await page.getByRole("button", { name: "刷新", exact: true }).click();
  await expect(page.locator(".creator-refresh-status")).toContainText("已刷新项目状态", { timeout: 60_000 });
  const reply = page.waitForResponse(response => new URL(response.url()).pathname === "/__creator/run" && response.request().method() === "POST", { timeout: 120_000 });
  await input.fill("这是刷新后的只读验收。请调用 inspect_app_ui_model 检查当前项目，用一句话说明根布局类型。不要修改任何文件，不要执行安装、同步或修复操作。");
  await page.getByRole("button", { name: "发送", exact: true }).click();
  const response = await reply;
  const stream = await response.text();
  await writeFile(path.join(evidence, "dialogue-events.sse"), stream);
  expect(response.ok()).toBe(true);
  expect(stream).toContain('"RUN_FINISHED"');
  expect(stream).not.toContain('"RUN_ERROR"');
  expect(stream).toContain("inspect_app_ui_model");
  await expect(input).toBeEnabled({ timeout: 30_000 });
  await page.screenshot({ path: path.join(evidence, "after-refresh-dialogue.png"), fullPage: true });
  expect(await readFile(file, "utf8")).toBe(before);
  expect(errors).toEqual([]);
});
