import { readdir, readFile, writeFile, mkdir, rename, lstat } from "node:fs/promises";
import path from "node:path";
import { randomUUID } from "node:crypto";
import { readAgentUIProjectConfig } from "./ui-project/project-mode";
import { resolveAgentUIProjectPaths } from "./ui-project/agent-ui-project-paths";
import { assertNoSymbolicLinkTraversal } from "./ui-project/source-registry/path-policy";

/** Explicit installation-time imports; no runtime discovery or automatic permission. */
export async function writeGeneratedFrontendToolRegistries(projectRoot: string): Promise<void> {
  const project = await readAgentUIProjectConfig(projectRoot);
  const paths = resolveAgentUIProjectPaths(projectRoot, project.config);
  const sourceRoot = path.dirname(paths.pluginsRoot);
  for (const [directory, output, exportName, typeName, typeImport, extension] of [
    ["agent-contract/frontend-tools", "agent-contract/frontend-tools.generated.ts", "frontendTools", "readonly AppFrontendToolDefinition<any>[]", 'import type { AppFrontendToolDefinition } from "../runtime/tools";', ".ts"],
    ["agent-ui/conversation/frontend-tool-uis", "agent-ui/conversation/frontend-tool-uis.generated.ts", "frontendToolUIs", "ConversationFrontendToolUIRegistry", 'import type { ConversationFrontendToolUIRegistry } from "@agent-ui/runtime-conversation";', ".tsx"],
  ] as const) {
    await assertNoSymbolicLinkTraversal(sourceRoot, directory);
    const entries = await readdir(path.join(sourceRoot, directory), { withFileTypes: true }).catch(error => {
      if (error.code === "ENOENT") return []; throw error;
    });
    const modules = entries.filter(entry => entry.isFile() && entry.name.endsWith(extension)).map(entry => entry.name).sort();
    for (const file of modules) {
      if (!/^[a-z][a-z0-9-]*\.(ts|tsx)$/.test(file)) throw new Error(`Invalid frontend tool module: ${file}`);
    }
    const imports = modules.map((file, i) => `import { ${exportName} as resource${i} } from "./${path.basename(directory)}/${file.slice(0, -extension.length)}";`);
    const value = exportName === "frontendTools" ? `[${modules.map((_, i) => `...resource${i}`).join(", ")}]`
      : `mergeRegistries([${modules.map((_, i) => `resource${i}`).join(", ")}])`;
    const merger = exportName === "frontendToolUIs" ? `
function mergeRegistries(resources: ConversationFrontendToolUIRegistry[]): ConversationFrontendToolUIRegistry {
  const registry: { -readonly [K in keyof ConversationFrontendToolUIRegistry]: ConversationFrontendToolUIRegistry[K] } = {};
  for (const resource of resources) for (const [name, renderer] of Object.entries(resource)) {
    if (Object.hasOwn(registry, name)) throw new Error(\`Duplicate frontend tool UI: \${name}\`);
    registry[name] = renderer;
  }
  return registry;
}
` : "";
    const source = ["// Generated by explicit scenario resource installation.", typeImport, ...imports, merger,
      `export const generated${exportName[0]!.toUpperCase()}${exportName.slice(1)}: ${typeName} = ${value};`, ""].join("\n");
    await assertNoSymbolicLinkTraversal(sourceRoot, output);
    const destination = path.join(sourceRoot, output);
    const old = await readFile(destination, "utf8").catch(error => { if (error.code === "ENOENT") return undefined; throw error; });
    if (old === source) continue;
    if (old !== undefined && !(await lstat(destination)).isFile()) throw new Error("Generated registry must be a regular file");
    await mkdir(path.dirname(destination), { recursive: true });
    const temporary = `${destination}.${randomUUID()}.tmp`;
    await writeFile(temporary, source);
    await rename(temporary, destination);
  }
}
