import { cp, mkdir, mkdtemp, readFile, rm, symlink, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { tmpdir } from "node:os";
import { afterEach, expect, it } from "vitest";
import { loadAgentUISourceRegistry, resolveAgentUISourceItemClosure } from "@agent-ui/source-registry";
import { installMockResource, inspectScenarioResources } from "../scripts/ui-project/install-scenario-resources";
import { mergeOptionalResourceInspection, resourcePaths } from "../scripts/ui-project/optional-resource-paths";
import { inspectAgentUISources } from "../scripts/ui-project/source-registry";
import { inspectUIComposition } from "../scripts/ui-project/project-inspector";
import { inspectMockDemoCompatibility } from "../../../packages/creator/src/mock/demo-compatibility";

const exampleRoot = fileURLToPath(new URL("..", import.meta.url));
const roots: string[] = [];
afterEach(async () => { await Promise.all(roots.splice(0).map(root => rm(root, { recursive: true, force: true }))); });

async function fixture() {
  const root = await mkdtemp(path.join(tmpdir(), "legacy-a2ui-readiness-")); roots.push(root);
  for (const directory of ["framework", "runtime", "plugins", "services", "application", "app-ui", "agent-ui", "src"]) {
    await cp(path.join(exampleRoot, directory), path.join(root, directory), { recursive: true });
  }
  const pkg = JSON.parse(await readFile(path.join(exampleRoot, "package.json"), "utf8"));
  await writeFile(path.join(root, "package.json"), JSON.stringify(pkg));
  await mkdir(path.join(root, "node_modules"));
  for (const name of Object.keys({ ...pkg.dependencies, ...pkg.devDependencies })) {
    const destination = path.join(root, "node_modules", name);
    await mkdir(path.dirname(destination), { recursive: true });
    await symlink(path.join(exampleRoot, "node_modules", name), destination, "dir");
  }
  await mkdir(path.join(root, ".agent-ui"));
  await writeFile(path.join(root, ".agent-ui/project.json"), JSON.stringify({ version: "1", mode: "platform" }));
  const registry = await loadAgentUISourceRegistry();
  const foundations = resolveAgentUISourceItemClosure(registry, "integration/a2ui").filter(item => item.kind === "foundation");
  for (const file of foundations.flatMap(item => item.loadedFiles)) {
    const target = path.join(root, file.target);
    await mkdir(path.dirname(target), { recursive: true }); await writeFile(target, file.content);
  }
  return { root, foundations };
}

it("makes legacy A2UI ready through the real Workbench merge without adopting Host foundations", async () => {
  const { root, foundations } = await fixture();
  async function compatibility() {
    const composition = await inspectUIComposition(root);
    const normal = await inspectAgentUISources(root);
    const resources = await inspectScenarioResources(root);
    const sources = await mergeOptionalResourceInspection(normal, resources);
    return { normal, resources, sources, requirement: inspectMockDemoCompatibility(composition, sources).requirements.find(item => item.id === "a2ui")! };
  }
  expect((await compatibility()).requirement.status).toBe("missing");
  // Derived registries are regenerated by the existing installer. Snapshot the
  // Host implementation files; assert generated integration/permission output below.
  const hostFiles = foundations.flatMap(item => item.loadedFiles)
    .filter(file => !file.target.includes(".generated."));
  const foundationBytes = () => Promise.all(hostFiles.map(file => readFile(path.join(root, file.target))));
  const before = await foundationBytes();
  const modelBefore = await readFile(path.join(root, "app-ui/app-ui.json"));
  await installMockResource(root, "integration/a2ui");
  const result = await compatibility();
  expect(result.requirement.status).toBe("ready");
  expect(result.requirement.plugin).toBeUndefined();
  expect(result.requirement.scenarioIds).toEqual(expect.arrayContaining(["a2ui-interactive-order", "a2ui-form-controls"]));
  const dependencyId = "agent-component/assistant-ui-generative-ui";
  // Normal inspection sees existing, unowned source. The optional lock owns it.
  expect(result.normal.items.find(item => item.id === dependencyId)).toMatchObject({ status: "blocked" });
  for (const id of [dependencyId, "integration/generative-ui", "integration/a2ui"]) {
    const resource = result.resources.items.find(item => item.id === id)!;
    expect(resource.installedVersion).toBeDefined();
    expect(result.sources.items.find(item => item.id === id)).toBe(resource);
    expect(resource).toMatchObject({ status: "managed", dependencyIssues: [] });
  }
  for (const foundation of foundations) {
    const provided = result.resources.items.find(item => item.id === foundation.id)!;
    expect(provided.installedVersion).toBeDefined();
    expect(result.sources.items.find(item => item.id === foundation.id)).toBe(provided);
  }
  const { config } = await resourcePaths(root);
  expect(config.agentUI.metadataRoot).toBe(".agent-ui/scenario-resources");
  const lock = JSON.parse(await readFile(path.join(root, config.agentUI.metadataRoot, "source-lock.json"), "utf8"));
  expect(Object.keys(lock.items).sort()).toEqual([
    "agent-component/assistant-ui-generative-ui", "integration/a2ui", "integration/generative-ui",
  ]);
  await expect(readFile(path.join(root, ".agent-ui/source-lock.json"))).rejects.toMatchObject({ code: "ENOENT" });
  expect(await foundationBytes()).toEqual(before);
  expect(await readFile(path.join(root, "app-ui/app-ui.json"))).toEqual(modelBefore);
  expect(await readFile(path.join(root, "agent-ui/conversation/integrations.generated.tsx"), "utf8"))
    .toContain('from "./integrations/a2ui"');
  const tools = await readFile(path.join(root, "agent-contract/frontend-tools.generated.ts"), "utf8");
  expect(tools).not.toContain("present");
  expect(tools).not.toContain("prompt_user");
});
