/**
 * Generated by scripts/generate-plugin-registry.ts from plugins/* capabilities.
 * Do not edit this file by hand.
 */
import { createPluginCapabilityCatalog } from "../runtime/composition";

export const capabilityCatalogRevision = "a99ec68159475510cbb5037f5483acbb74702799c36e5cef21b65e10b17dd870";

export const pluginCapabilityCatalog = createPluginCapabilityCatalog([
  {
    manifest: {
      "id": "assistant-ui-add-attachment-action",
      "name": "Assistant UI Add Attachment Action",
      "description": "Adds assistant-ui's attachment picker to the conversation composer.",
      "version": "1.0.0",
      "capabilities": [
        "conversation-composer-leading-action"
      ],
      "authoring": {
        "intents": [
          "add attachments to the conversation composer"
        ],
        "visualRole": "conversation composer attachment action",
        "defaultPlacement": {
          "type": "plugin_slot",
          "parentPluginId": "assistant-ui-composer",
          "slot": "leadingActions"
        }
      }
    },
    provides: [],
    inject: [],
    optionalInject: [],
    loadDefinition: () =>
      import("./assistant-ui-add-attachment-action/definition").then(
        ({ default: definition }) => definition,
      ),
  },
  {
    manifest: {
      "id": "assistant-ui-composer",
      "name": "Assistant UI Composer",
      "description": "Renders the canonical assistant-ui conversation composer with composable action Slots.",
      "version": "1.0.0",
      "capabilities": [
        "conversation-composer"
      ],
      "authoring": {
        "intents": [
          "show the primary conversation composer",
          "compose conversation input actions"
        ],
        "visualRole": "conversation composer",
        "defaultPlacement": {
          "type": "plugin_slot",
          "parentPluginId": "conversation-surface",
          "slot": "composer"
        }
      },
      "slots": {
        "children": {
          "beforeInput": {
            "description": "Content displayed between attachments and the composer input.",
            "cardinality": "many",
            "optional": true,
            "accepts": {
              "anyOfCapabilities": [
                "conversation-composer-before-input"
              ]
            }
          },
          "leadingActions": {
            "description": "Inline actions displayed on the leading side of the composer.",
            "cardinality": "many",
            "optional": true,
            "accepts": {
              "anyOfCapabilities": [
                "conversation-composer-leading-action"
              ]
            }
          },
          "trailingActions": {
            "description": "Inline actions displayed before the composer submit action.",
            "cardinality": "many",
            "optional": true,
            "accepts": {
              "anyOfCapabilities": [
                "conversation-composer-trailing-action"
              ]
            }
          },
          "submitAction": {
            "description": "The primary send or stop action for the composer.",
            "cardinality": "one",
            "optional": true,
            "accepts": {
              "anyOfCapabilities": [
                "conversation-composer-submit-action"
              ]
            }
          }
        }
      }
    },
    provides: [],
    inject: [],
    optionalInject: [],
    loadDefinition: () =>
      import("./assistant-ui-composer/definition").then(
        ({ default: definition }) => definition,
      ),
  },
  {
    manifest: {
      "id": "assistant-ui-copy-action",
      "name": "Assistant UI Copy Action",
      "description": "Copies the current assistant message through assistant-ui.",
      "version": "1.0.0",
      "capabilities": [
        "conversation-message-action"
      ],
      "authoring": {
        "intents": [
          "copy assistant message content"
        ],
        "visualRole": "assistant message copy action",
        "defaultPlacement": {
          "type": "plugin_slot",
          "parentPluginId": "assistant-ui-message-footer",
          "slot": "actions"
        }
      }
    },
    provides: [],
    inject: [],
    optionalInject: [],
    loadDefinition: () =>
      import("./assistant-ui-copy-action/definition").then(
        ({ default: definition }) => definition,
      ),
  },
  {
    manifest: {
      "id": "assistant-ui-dictation-action",
      "name": "Assistant UI Dictation Action",
      "description": "Adds assistant-ui dictation controls to the conversation composer.",
      "version": "1.0.0",
      "capabilities": [
        "conversation-composer-trailing-action"
      ],
      "authoring": {
        "intents": [
          "add voice dictation to the conversation composer"
        ],
        "visualRole": "conversation composer dictation action",
        "defaultPlacement": {
          "type": "plugin_slot",
          "parentPluginId": "assistant-ui-composer",
          "slot": "trailingActions"
        }
      }
    },
    provides: [],
    inject: [],
    optionalInject: [],
    loadDefinition: () =>
      import("./assistant-ui-dictation-action/definition").then(
        ({ default: definition }) => definition,
      ),
  },
  {
    manifest: {
      "id": "assistant-ui-export-markdown-action",
      "name": "Assistant UI Export Markdown Action",
      "description": "Exports the current assistant message as Markdown through assistant-ui.",
      "version": "1.0.0",
      "capabilities": [
        "conversation-message-action"
      ],
      "authoring": {
        "intents": [
          "export an assistant message as Markdown"
        ],
        "visualRole": "assistant message Markdown export action",
        "defaultPlacement": {
          "type": "plugin_slot",
          "parentPluginId": "assistant-ui-message-footer",
          "slot": "actions"
        }
      }
    },
    provides: [],
    inject: [],
    optionalInject: [],
    loadDefinition: () =>
      import("./assistant-ui-export-markdown-action/definition").then(
        ({ default: definition }) => definition,
      ),
  },
  {
    manifest: {
      "id": "assistant-ui-message-footer",
      "name": "Assistant UI Message Footer",
      "description": "Renders the canonical assistant message footer and its composable actions.",
      "version": "1.0.0",
      "capabilities": [
        "conversation-assistant-message-footer-renderer"
      ],
      "requiresRenderScope": true,
      "authoring": {
        "intents": [
          "show assistant message branch and action controls",
          "compose assistant message footer actions"
        ],
        "visualRole": "assistant message footer",
        "defaultPlacement": {
          "type": "plugin_slot",
          "parentPluginId": "conversation-surface",
          "slot": "assistantMessageFooter"
        }
      },
      "slots": {
        "children": {
          "actions": {
            "description": "Actions displayed in the assistant message footer.",
            "cardinality": "many",
            "optional": true,
            "accepts": {
              "anyOfCapabilities": [
                "conversation-message-action"
              ]
            }
          }
        }
      }
    },
    provides: [],
    inject: [],
    optionalInject: [],
    loadDefinition: () =>
      import("./assistant-ui-message-footer/definition").then(
        ({ default: definition }) => definition,
      ),
  },
  {
    manifest: {
      "id": "assistant-ui-reasoning",
      "name": "Assistant UI Reasoning Renderer",
      "description": "Displays one assistant-ui reasoning group with canonical presentation.",
      "version": "1.0.0",
      "capabilities": [
        "conversation-reasoning-renderer"
      ],
      "requiresRenderScope": true,
      "authoring": {
        "intents": [
          "show the reasoning process",
          "restore reasoning presentation",
          "show deep thinking"
        ],
        "visualRole": "assistant reasoning presentation",
        "defaultPlacement": {
          "type": "plugin_slot",
          "parentPluginId": "conversation-surface",
          "slot": "reasoningGroup"
        }
      }
    },
    provides: [],
    inject: [],
    optionalInject: [],
    loadDefinition: () =>
      import("./assistant-ui-reasoning/definition").then(
        ({ default: definition }) => definition,
      ),
  },
  {
    manifest: {
      "id": "assistant-ui-reload-action",
      "name": "Assistant UI Reload Action",
      "description": "Regenerates the current assistant message through assistant-ui.",
      "version": "1.0.0",
      "capabilities": [
        "conversation-message-action"
      ],
      "authoring": {
        "intents": [
          "regenerate an assistant message"
        ],
        "visualRole": "assistant message reload action",
        "defaultPlacement": {
          "type": "plugin_slot",
          "parentPluginId": "assistant-ui-message-footer",
          "slot": "actions"
        }
      }
    },
    provides: [],
    inject: [],
    optionalInject: [],
    loadDefinition: () =>
      import("./assistant-ui-reload-action/definition").then(
        ({ default: definition }) => definition,
      ),
  },
  {
    manifest: {
      "id": "assistant-ui-submit-action",
      "name": "Assistant UI Submit Action",
      "description": "Adds assistant-ui send and stop controls to the conversation composer.",
      "version": "1.0.0",
      "capabilities": [
        "conversation-composer-submit-action"
      ],
      "authoring": {
        "intents": [
          "add the conversation composer send and stop action"
        ],
        "visualRole": "conversation composer submit action",
        "defaultPlacement": {
          "type": "plugin_slot",
          "parentPluginId": "assistant-ui-composer",
          "slot": "submitAction"
        }
      }
    },
    provides: [],
    inject: [],
    optionalInject: [],
    loadDefinition: () =>
      import("./assistant-ui-submit-action/definition").then(
        ({ default: definition }) => definition,
      ),
  },
  {
    manifest: {
      "id": "assistant-ui-tool-fallback",
      "name": "Assistant UI Tool Fallback Renderer",
      "description": "Displays an unregistered tool call with canonical assistant-ui presentation.",
      "version": "1.0.0",
      "capabilities": [
        "conversation-tool-fallback-renderer"
      ],
      "requiresRenderScope": true,
      "authoring": {
        "intents": [
          "show unregistered tool calls",
          "restore tool fallback presentation"
        ],
        "visualRole": "assistant tool fallback presentation",
        "defaultPlacement": {
          "type": "plugin_slot",
          "parentPluginId": "conversation-surface",
          "slot": "toolFallback"
        }
      }
    },
    provides: [],
    inject: [],
    optionalInject: [],
    loadDefinition: () =>
      import("./assistant-ui-tool-fallback/definition").then(
        ({ default: definition }) => definition,
      ),
  },
  {
    manifest: {
      "id": "assistant-ui-tool-group",
      "name": "Assistant UI Tool Group Renderer",
      "description": "Displays one assistant-ui tool group with canonical presentation.",
      "version": "1.0.0",
      "capabilities": [
        "conversation-tool-group-renderer"
      ],
      "requiresRenderScope": true,
      "authoring": {
        "intents": [
          "show grouped tool activity",
          "restore tool group presentation"
        ],
        "visualRole": "assistant tool group presentation",
        "defaultPlacement": {
          "type": "plugin_slot",
          "parentPluginId": "conversation-surface",
          "slot": "toolGroup"
        }
      }
    },
    provides: [],
    inject: [],
    optionalInject: [],
    loadDefinition: () =>
      import("./assistant-ui-tool-group/definition").then(
        ({ default: definition }) => definition,
      ),
  },
  {
    manifest: {
      "id": "conversation-data-source",
      "name": "Conversation Data Source",
      "description": "Provides conversation history data through an application-owned API.",
      "version": "1.0.0",
      "capabilities": [
        "headless"
      ],
      "authoring": {
        "intents": [
          "provide persistent conversation history data to conversation capabilities"
        ]
      }
    },
    provides: ["agent-ui.conversation-data-source"],
    inject: [],
    optionalInject: [],
    loadDefinition: () =>
      import("./conversation-data-source/definition").then(
        ({ default: definition }) => definition,
      ),
  },
  {
    manifest: {
      "id": "conversation-service",
      "name": "Conversation Service",
      "description": "Provides shared application conversation state and history navigation independently from presentation plugins.",
      "version": "1.0.0",
      "capabilities": [
        "headless",
        "conversation-service",
        "plugin-service-provider"
      ],
      "authoring": {
        "intents": [
          "provide shared conversation management state and history navigation"
        ]
      }
    },
    provides: ["agent-ui.conversations"],
    inject: ["agent-ui.conversation-data-source"],
    optionalInject: [],
    loadDefinition: () =>
      import("./conversation-service/definition").then(
        ({ default: definition }) => definition,
      ),
  },
  {
    manifest: {
      "id": "conversation-suggestions",
      "name": "Conversation Suggestions",
      "description": "Renders starter prompts through the Conversation public surface.",
      "version": "1.0.0",
      "capabilities": [
        "conversation-suggestions"
      ],
      "authoring": {
        "intents": [
          "show starter prompts and suggested conversation actions"
        ],
        "visualRole": "conversation empty-state suggestions",
        "defaultPlacement": {
          "type": "plugin_slot",
          "parentPluginId": "conversation-surface",
          "slot": "emptySuggestions"
        }
      }
    },
    provides: [],
    inject: [],
    optionalInject: [],
    loadDefinition: () =>
      import("./conversation-suggestions/definition").then(
        ({ default: definition }) => definition,
      ),
  },
  {
    manifest: {
      "id": "conversation-surface",
      "name": "Conversation Surface",
      "description": "组合 Live 与只读 History 会话的空状态、消息时间线与输入区。",
      "version": "2.1.0",
      "capabilities": [
        "conversation-surface"
      ],
      "authoring": {
        "intents": [
          "show the primary live and historical conversation experience"
        ],
        "visualRole": "primary conversation surface",
        "recommendedSize": {
          "width": "minmax(0, 1fr)"
        }
      },
      "slots": {
        "children": {
          "emptyWelcome": {
            "description": "Welcome content displayed when the conversation is empty.",
            "cardinality": "one",
            "optional": true
          },
          "emptySuggestions": {
            "description": "Suggested prompts or actions displayed when the conversation is empty.",
            "cardinality": "many",
            "optional": true,
            "accepts": {
              "anyOfCapabilities": [
                "conversation-suggestions"
              ]
            }
          },
          "headerActions": {
            "description": "Top-right controls displayed on the Conversation surface.",
            "cardinality": "many",
            "optional": true,
            "accepts": {
              "anyOfCapabilities": [
                "theme-control"
              ]
            }
          },
          "composer": {
            "description": "Primary conversation composer.",
            "cardinality": "one",
            "optional": true,
            "accepts": {
              "anyOfCapabilities": [
                "conversation-composer"
              ]
            }
          },
          "reasoningGroup": {
            "description": "Renderer for one assistant reasoning group.",
            "cardinality": "one",
            "mode": "renderer",
            "optional": true,
            "accepts": {
              "anyOfCapabilities": [
                "conversation-reasoning-renderer"
              ]
            }
          },
          "toolGroup": {
            "description": "Renderer for one assistant tool group.",
            "cardinality": "one",
            "mode": "renderer",
            "optional": true,
            "accepts": {
              "anyOfCapabilities": [
                "conversation-tool-group-renderer"
              ]
            }
          },
          "toolFallback": {
            "description": "Renderer for an unnamed tool UI fallback.",
            "cardinality": "one",
            "mode": "renderer",
            "optional": true,
            "accepts": {
              "anyOfCapabilities": [
                "conversation-tool-fallback-renderer"
              ]
            }
          },
          "assistantMessageFooter": {
            "description": "Renderer for the assistant message footer.",
            "cardinality": "one",
            "mode": "renderer",
            "optional": true,
            "accepts": {
              "anyOfCapabilities": [
                "conversation-assistant-message-footer-renderer"
              ]
            }
          }
        }
      },
      "data": {
        "messages": true
      }
    },
    provides: [],
    inject: ["agent-ui.conversations"],
    optionalInject: ["agent-ui.theme"],
    loadDefinition: () =>
      import("./conversation-surface/definition").then(
        ({ default: definition }) => definition,
      ),
  },
  {
    manifest: {
      "id": "conversation-thread-list",
      "name": "Conversation Thread List",
      "description": "Uses the public Conversation thread list with AgentUICreator policy and data binding.",
      "version": "1.0.0",
      "capabilities": [
        "conversation-create",
        "conversation-history",
        "conversation-selection",
        "plugin-service-consumer"
      ],
      "authoring": {
        "intents": [
          "add conversation management",
          "browse conversation history",
          "select an existing conversation",
          "start a new conversation"
        ],
        "visualRole": "conversation navigation",
        "defaultPlacement": {
          "type": "relative",
          "relation": "before",
          "anchorPluginId": "conversation-surface"
        },
        "recommendedSize": {
          "width": "280px"
        }
      }
    },
    provides: [],
    inject: ["agent-ui.conversations"],
    optionalInject: ["agent-ui.theme"],
    loadDefinition: () =>
      import("./conversation-thread-list/definition").then(
        ({ default: definition }) => definition,
      ),
  },
  {
    manifest: {
      "id": "locale-provider",
      "name": "Headless Locale Service Provider",
      "description": "Provides the shared application locale service to UI plugins.",
      "version": "1.0.0",
      "capabilities": [
        "plugin-service-provider",
        "locale",
        "headless"
      ]
    },
    provides: ["agent-ui.locale"],
    inject: [],
    optionalInject: [],
    loadDefinition: () =>
      import("./locale-provider/definition").then(
        ({ default: definition }) => definition,
      ),
  },
  {
    manifest: {
      "id": "theme-provider",
      "name": "Headless Theme Service Provider",
      "description": "Provides the shared light and dark theme service to other UI plugins.",
      "version": "1.0.0",
      "capabilities": [
        "plugin-service-provider",
        "theme",
        "headless"
      ],
      "authoring": {
        "intents": [
          "provide shared light and dark theme state"
        ]
      }
    },
    provides: ["agent-ui.theme"],
    inject: [],
    optionalInject: [],
    loadDefinition: () =>
      import("./theme-provider/definition").then(
        ({ default: definition }) => definition,
      ),
  },
  {
    manifest: {
      "id": "theme-switch",
      "name": "Theme Switch",
      "description": "Calls the shared theme service exposed by another UI plugin.",
      "version": "1.0.0",
      "capabilities": [
        "theme-control",
        "plugin-service-consumer"
      ],
      "authoring": {
        "intents": [
          "let the user switch between light and dark themes"
        ],
        "visualRole": "theme control",
        "defaultPlacement": {
          "type": "plugin_slot",
          "parentPluginId": "conversation-surface",
          "slot": "headerActions"
        }
      }
    },
    provides: [],
    inject: ["agent-ui.theme"],
    optionalInject: ["agent-ui.locale"],
    loadDefinition: () =>
      import("./theme-switch/definition").then(
        ({ default: definition }) => definition,
      ),
  },
]);
