/**
 * Generated by scripts/generate-plugin-registry.ts from AppUIModel.
 * Do not edit this file by hand.
 */
import pluginDefinition0 from "./assistant-ui-thread-list/definition";
import pluginDefinition1 from "./conversation-data-source/definition";
import pluginDefinition2 from "./conversation-service/definition";
import pluginDefinition3 from "./conversation-surface/definition";
import pluginDefinition4 from "./theme-provider/definition";
import pluginDefinition5 from "./theme-switch/definition";

export const pluginDefinitions = [
  pluginDefinition0,
  pluginDefinition1,
  pluginDefinition2,
  pluginDefinition3,
  pluginDefinition4,
  pluginDefinition5,
] as const;
