/**
 * Generated by scripts/generate-plugin-registry.ts from AppUIModel.
 * Do not edit this file by hand.
 */
import pluginDefinition0 from "./agent-composer/definition";
import pluginDefinition1 from "./agent-conversations/definition";
import pluginDefinition2 from "./agent-message-list/definition";
import pluginDefinition3 from "./agent-reasoning/definition";
import pluginDefinition4 from "./agent-suggestions/definition";
import pluginDefinition5 from "./agent-thread-welcome/definition";
import pluginDefinition6 from "./agent-tool/definition";
import pluginDefinition7 from "./agent-tool-activity/definition";
import pluginDefinition8 from "./agent-tool-detail/definition";
import pluginDefinition9 from "./antd-x-resources/definition";
import pluginDefinition10 from "./antd-x-theme-provider/definition";
import pluginDefinition11 from "./antd-x-theme-switch/definition";
import pluginDefinition12 from "./conversation-controller/definition";
import pluginDefinition13 from "./conversation-data-source/definition";
import pluginDefinition14 from "./conversation-surface/definition";
import pluginDefinition15 from "./mock-auth-login/definition";
import pluginDefinition16 from "./workspace-inspector/definition";

export const pluginDefinitions = [
  pluginDefinition0,
  pluginDefinition1,
  pluginDefinition2,
  pluginDefinition3,
  pluginDefinition4,
  pluginDefinition5,
  pluginDefinition6,
  pluginDefinition7,
  pluginDefinition8,
  pluginDefinition9,
  pluginDefinition10,
  pluginDefinition11,
  pluginDefinition12,
  pluginDefinition13,
  pluginDefinition14,
  pluginDefinition15,
  pluginDefinition16,
] as const;
